### PR TITLE
[WIP] Powershell activation scripts for ROS2

### PR DESCRIPTION
**Pull request by Tobias-Fischer**
Fix https://github.com/RoboStack/ros-galactic/issues/91

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
Hi @traversaro - I have blindly written the activate/deactivate ps1 scripts. Is there any chance you could give them a go? If they work I can trigger a rebuild of the ros-workspace package in the Galactic repo so that they are built and installed correctly.

@wolfv @traversaro - I have also no idea how the `ps1.in` scripts are converted to "pure" `.ps1` scripts and whether I am missing some line prefixes in the `ps1.in` files so that the conversion happens correctly. (I modified the python scripts to trigger the conversion but didn't dig how it actually happens).

**Comment by traversaro** [comment]
> Is there any chance you could give them a go?

Just to understand, you mean use vinca to generate the recipes, build them via boa and then test them, right?

**Comment by Tobias-Fischer** [comment]
I think to start with it would be sufficient to just call the (de-)activate scripts from a Powershell (i.e. copy the contents in a file somewhere) and see whether they 1) run without errors, and 2) set the intended environment variables and enable ROS2 to run. Once we have confirmed this, I can produce new packages and we can see whether the automated activation works too.

**Comment by Tobias-Fischer** [comment]
Hey @traversaro @wolfv - did you have a chance to look at this?

**Comment by Tobias-Fischer** [comment]
Kind ping @traversaro @wolfv

**Comment by traversaro** [comment]
> I think to start with it would be sufficient to just call the (de-)activate scripts from a Powershell (i.e. copy the contents in a file somewhere) and see whether they 1) run without errors, and 2) set the intended environment variables and enable ROS2 to run. Once we have confirmed this, I can produce new packages and we can see whether the automated activation works too.

I did this (by commenting the `local_setup.ps1` inclusion), and the variables are indeed set by `activate.ps1` and unset by `deactivate.ps1` .

**Review by traversaro — APPROVED** [review]

**Comment by Tobias-Fischer** [comment]
Thanks for testing!

**Pull request merged**
