### PR TITLE
Fix python install dir using SP_DIR

### PR DESCRIPTION
**Pull request by Tobias-Fischer**
Fix https://github.com/RoboStack/ros-galactic/issues/40

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
Would be great if you have a look @wolfv

**Comment by wolfv** [comment]
I think this is great (but has the potential to break everything :)

But I think we should go for it!

**Comment by wolfv** [comment]
Should we do that for catkin, too?

**Comment by Tobias-Fischer** [comment]
Yes .. could indeed break everything. But seeing we're planning on a full rebuild, we'd notice that very early on ;).

Re catkin: I don't think it supports that - `PYTHON_INSTALL_DIR` seems to be specific to ament. But happy to be convinced otherwise :)

**Comment by wolfv** [comment]
I thought that was a "CMake thing"

**Comment by wolfv** [comment]
I see it referenced quite a bit: https://github.com/ros/catkin/search?q=PYTHON_INSTALL_DIR

If it works as intended, I don't know.

**Comment by Tobias-Fischer** [comment]
It is! Yes, will amend the PR to include catkin as well tomorrow.

**Comment by Tobias-Fischer** [comment]
Cool, fixed the remaining instances.

I suggest to merge it in and just see what happens ... ;)

**Comment by wolfv** [comment]
Woop woop

**Pull request merged**
